//===-- VortexGPUIntrinsicOps.td ------------------------------*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file contains definitions of the intrinsic Ops for the VortexGPU dialect
//
//===----------------------------------------------------------------------===//

#ifndef VortexGPU_INTRINSIC_OPS
#define VortexGPU_INTRINSIC_OPS

include "VortexGPU.td"

//===----------------------------------------------------------------------===//
// VortexGPU Intrinsic op definitions
//===----------------------------------------------------------------------===//


#endif // VortexGPU_INTRINSIC_OPS
