//===-- Passes.td - VortexGPU pass definition file ------------*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef MLIR_DIALECT_VortexGPU_TRANSFORMS_PASSES_TD
#define MLIR_DIALECT_VortexGPU_TRANSFORMS_PASSES_TD

include "mlir/Pass/PassBase.td"
include "mlir/IR/EnumAttr.td"



#endif // MLIR_DIALECT_VortexGPU_TRANSFORMS_PASSES_TD
